name: scheduler
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - postgresql
  - libpq
  - sqlalchemy=2.0.23
  - alembic=1.13.1
  - pydantic=2.5.0
  - pytest=7.4.3
  - pytest-asyncio=0.21.1
  - pytest-cov=4.1.0
  - python-dotenv=1.0.0
  - setuptools<81
  - pip
  - pip:
    - psycopg[binary]==3.1.13
    - asyncpg==0.29.0
    - pytest-postgresql==7.0.2
    - fastapi==0.104.1
    - uvicorn[standard]==0.24.0
    - httpx==0.25.2
    - python-multipart==0.0.6
    - python-jose[cryptography]==3.3.0
    - passlib[bcrypt]==1.7.4
    - pydantic[email]==2.5.0