name: scheduler
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - psycopg2=2.9.9
  - sqlalchemy=2.0.23
  - alembic=1.13.1
  - pydantic=2.5.0
  - pytest=7.4.3
  - pytest-asyncio=0.21.1
  - pytest-cov=4.1.0
  - python-dotenv=1.0.0
  - pip
  - pip:
    - asyncpg==0.29.0
    - pytest-postgresql==5.0.0